services:
    gitkraken:
        container_name: gitkraken-vnc
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USERNAME: ${CURRENT_USER:-smanetagis}
                USER_UID: ${CURRENT_UID:-1000}
                USER_GID: ${CURRENT_GID:-1000}
#        user: "${CURRENT_UID:-1000}:${CURRENT_GID:-1000}"
        environment:
            - HOME=/home/${CURRENT_USER}
            - DISPLAY=:99
            - USERNAME=${CURRENT_USER:-smanetagis}
            - USER_UID=${CURRENT_UID:-1000}
            - USER_GID=${CURRENT_GID:-1000}
        volumes:
            - ./supervisord.conf:/etc/supervisor/supervisord.conf
            - ./gitkraken-config:/home/${CURRENT_USER}/.config/GitKraken
            - ./gitkraken-data:/home/${CURRENT_USER}/.gitkraken
            - ./../:/home/${CURRENT_USER}/workspace
#            - ./datas:/home/${CURRENT_USER}/.gitkraken
            - ./../.ssh:/ssh:ro
        ports:
            - "6080:6080"  # noVNC (accès web)
            - "5900:5900"  # VNC direct (optionnel)
        shm_size: '2gb'
        security_opt:
            - seccomp:unconfined
        cap_add:
            - SYS_ADMIN
        entrypoint: [ "/bin/bash", "/entrypoint.sh" ]
